const Colors = {
  lightTheme: {
    background: '#ffffff',
    lightGray: '#cccccc',
    darkText: '#333333',
    mediumText: '#666666',
    lightText: '#aaaaaa',
    brightBlue: '#007bff',
    saveButton: '#28a745',
    dangerButton: '#dc3545',
    logoutBackground: '#ffffff',
    deleteIconColor: '#900',
    statusPending: '#ffcccc',
    statusInProgress: '#fff3cd',
    statusDone: '#d4edda',
    modalOverlay: 'rgba(0,0,0,0.4)',
    signupTitle: '#004466',
    signupBackground: '#A7C7E7',
    MovieCardBackground: '#f0f9ff',
    MovieTitle: '#2d3748',
    MovieRelease: '#718096',
    MovieOverview: '#4a5568',
  },
  darkTheme: {
    background: '#000000',
    lightGray: '#ffffff',
    darkText: '#ffffff',
    mediumText: '#ffffff',
    lightText: '#ffffff',
    brightBlue: '#007bff',
    saveButton: '#28a745',
    dangerButton: '#ffffff',
    logoutBackground: '#900',
    deleteIconColor: '#900',
    statusPending: '#9e0826',
    statusInProgress: '#728101',
    statusDone: '#046424',
    modalOverlay: 'rgba(0,0,0,0.4)',
    signupTitle: '#004466',
    signupBackground: '#A7C7E7',
    MovieCardBackground: '#4d4c4c',
    MovieTitle: '#ffffff',
    MovieRelease: '#ffffff',
    MovieOverview: '#ffffff',
  },
};

export default Colors;
export type AppColorsType = typeof Colors.darkTheme | typeof Colors.lightTheme;
